apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

annotations:
  meta.helm.sh/release-name: {{ .Release.Name }}
  meta.helm.sh/release-namespace: {{ .Release.Namespace }}

labels:
  app.kubernetes.io/managed-by: Helm