apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  customers-db-mysql: {{ .Values.customersservice.dbpassword }}
  vets-db-mysql: {{ .Values.vetsservice.dbpassword }}
  visits-db-mysql: {{ .Values.visitsservice.dbpassword }}