apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: production
type: Opaque
data:
  customers-db-mysql: {{ .Values.customersservice.dbpassword }}
  vets-db-mysql: {{ .Values.vetsservice.dbpassword }}
  visits-db-mysql: {{ .Values.visitsservice.dbpassword }}

---

apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: staging
type: Opaque
data:
  customers-db-mysql: {{ .Values.customersservice.dbpassword }}
  vets-db-mysql: {{ .Values.vetsservice.dbpassword }}
  visits-db-mysql: {{ .Values.visitsservice.dbpassword }}
