apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "fullname" . }}
  type: {{ .Values.service.type }}
