name: Build Docker Images

on:
  push:
    branches: [ "staging", "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker pull springcommunity/spring-petclinic-config-server
          docker pull springcommunity/spring-petclinic-discovery-server
          docker pull springcommunity/spring-petclinic-customers-service
          docker pull springcommunity/spring-petclinic-visits-service
          docker pull springcommunity/spring-petclinic-vets-service
          docker pull springcommunity/spring-petclinic-api-gateway
          docker pull openzipkin/zipkin
          docker pull springcommunity/spring-petclinic-admin-server

          docker tag springcommunity/spring-petclinic-config-server $DOCKER_USERNAME/spring-petclinic-config-server:latest
          docker tag springcommunity/spring-petclinic-discovery-server $DOCKER_USERNAME/spring-petclinic-discovery-server:latest
          docker tag springcommunity/spring-petclinic-customers-service $DOCKER_USERNAME/spring-petclinic-customers-service:latest
          docker tag springcommunity/spring-petclinic-visits-service $DOCKER_USERNAME/spring-petclinic-visits-service:latest
          docker tag springcommunity/spring-petclinic-vets-service $DOCKER_USERNAME/spring-petclinic-vets-service:latest
          docker tag springcommunity/spring-petclinic-api-gateway $DOCKER_USERNAME/spring-petclinic-api-gateway:latest
          docker tag openzipkin/zipkin $DOCKER_USERNAME/zipkin:latest
          docker tag springcommunity/spring-petclinic-admin-server $DOCKER_USERNAME/spring-petclinic-admin-server:latest

          docker push $DOCKER_USERNAME/spring-petclinic-config-server:latest
          docker push $DOCKER_USERNAME/spring-petclinic-discovery-server:latest
          docker push $DOCKER_USERNAME/spring-petclinic-customers-service:latest
          docker push $DOCKER_USERNAME/spring-petclinic-visits-service:latest
          docker push $DOCKER_USERNAME/spring-petclinic-vets-service:latest
          docker push $DOCKER_USERNAME/spring-petclinic-api-gateway:latest
          docker push $DOCKER_USERNAME/zipkin:latest
          docker push $DOCKER_USERNAME/spring-petclinic-admin-server:latest
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Package and push helm chart to Amazon ECR
        run: |
          helm package petclinic
          helm push petclinic-0.0.1.tgz oci://844112306741.dkr.ecr.eu-west-3.amazonaws.com/
